sudo: required

env:
  - CABALVER=3.4 GHCVER=8.10.4

before_install:
  - sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER graphviz
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - travis_retry cabal update

install:
  - cabal install --only-dependencies --enable-tests --enable-benchmarks

script:
  - cabal build
  - cabal test
  - cabal sdist
